
version: '3.8'

services:
  prediction-api:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./prediction:/app
    environment:
      - FLASK_APP=predict_api.py
      - FLASK_ENV=development

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./chatbot:/app

  web-client:
    image: python:3.12-slim
    ports:
      - "8000:8000"
    volumes:
      - ./web-client:/app
    working_dir: /app
    command: python -m http.server 8000

networks:
  default:
    name: seamap-network